// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Vendas.Model
{
    public partial class DB_VENDAContext : DbContext
    {
        public DB_VENDAContext()
        {
        }

        public DB_VENDAContext(DbContextOptions<DB_VENDAContext> options)
            : base(options)
        {
        }

        public virtual DbSet<TBCategorias> TBCategorias { get; set; }
        public virtual DbSet<TBClientes> TBClientes { get; set; }
        public virtual DbSet<TBItens> TBItens { get; set; }
        public virtual DbSet<TBPedidos> TBPedidos { get; set; }
        public virtual DbSet<TBProdutos> TBProdutos { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder.UseSqlServer("Server=.\\SQLExpress;Database=DB_VENDAS;Trusted_Connection=True;trustservercertificate=true");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<TBCategorias>(entity =>
            {
                entity.Property(e => e.Descricao)
                    .IsRequired()
                    .HasMaxLength(20)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<TBClientes>(entity =>
            {
                entity.HasKey(e => e.Documento)
                    .HasName("PK__TBClient__AF73706C7DDBD846");

                entity.Property(e => e.Documento)
                    .HasMaxLength(14)
                    .IsUnicode(false);

                entity.Property(e => e.Email)
                    .IsRequired()
                    .HasMaxLength(60)
                    .IsUnicode(false);

                entity.Property(e => e.Nome)
                    .IsRequired()
                    .HasMaxLength(60)
                    .IsUnicode(false);

                entity.Property(e => e.Telefone)
                    .IsRequired()
                    .HasMaxLength(20)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<TBItens>(entity =>
            {
                entity.HasOne(d => d.IdPedidoNavigation)
                    .WithMany(p => p.TBItens)
                    .HasForeignKey(d => d.IdPedido)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__TBItens__IdPedid__2C3393D0");

                entity.HasOne(d => d.IdProdutoNavigation)
                    .WithMany(p => p.TBItens)
                    .HasForeignKey(d => d.IdProduto)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__TBItens__IdProdu__2D27B809");
            });

            modelBuilder.Entity<TBPedidos>(entity =>
            {
                entity.Property(e => e.Data).HasColumnType("datetime");

                entity.Property(e => e.DocCliente)
                    .IsRequired()
                    .HasMaxLength(14)
                    .IsUnicode(false);

                entity.Property(e => e.NumeroPedido)
                    .IsRequired()
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.HasOne(d => d.DocClienteNavigation)
                    .WithMany(p => p.TBPedidos)
                    .HasForeignKey(d => d.DocCliente)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__TBPedidos__DocCl__2E1BDC42");
            });

            modelBuilder.Entity<TBProdutos>(entity =>
            {
                entity.Property(e => e.Descricao)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.MimeType)
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.Unidade)
                    .IsRequired()
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.HasOne(d => d.IdCategoriaNavigation)
                    .WithMany(p => p.TBProdutos)
                    .HasForeignKey(d => d.IdCategoria)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__TBProduto__IdCat__2F10007B");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}