// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Vendas.Model
{
    public partial class TBCategorias
    {
        public TBCategorias()
        {
            TBProdutos = new HashSet<TBProdutos>();
        }

        public int Id { get; set; }
        public string Descricao { get; set; }

        public virtual ICollection<TBProdutos> TBProdutos { get; set; }
    }
}