// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Vendas.Model
{
    public partial class TBClientes
    {
        public TBClientes()
        {
            TBPedidos = new HashSet<TBPedidos>();
        }

        public string Documento { get; set; }
        public string Nome { get; set; }
        public string Telefone { get; set; }
        public string Email { get; set; }

        public virtual ICollection<TBPedidos> TBPedidos { get; set; }
    }
}