// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Vendas.Model
{
    public partial class TBItens
    {

        public int Id { get; set; }
        public int IdPedido { get; set; }
        public int IdProduto { get; set; }
        public double Quantidade { get; set; }

        public virtual TBPedidos IdPedidoNavigation { get; set; }
        public virtual TBProdutos IdProdutoNavigation { get; set; }
    }
}