// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Vendas.Model
{
    public partial class TBPedidos
    {
        public TBPedidos()
        {
            TBItens = new HashSet<TBItens>();
        }

        public int Id { get; set; }
        public string DocCliente { get; set; }
        public DateTime Data { get; set; }
        public string NumeroPedido { get; set; }

        public virtual TBClientes DocClienteNavigation { get; set; }
        public virtual ICollection<TBItens> TBItens { get; set; }
    }
}