// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Vendas.Model
{
    public partial class TBProdutos
    {
        public TBProdutos()
        {
            TBItens = new HashSet<TBItens>();
        }

        public int Id { get; set; }
        public int IdCategoria { get; set; }
        public string Descricao { get; set; }
        public string Unidade { get; set; }
        public byte[] Foto { get; set; }
        public string MimeType { get; set; }
        public double Preco { get; set; }

        public virtual TBCategorias IdCategoriaNavigation { get; set; }
        public virtual ICollection<TBItens> TBItens { get; set; }
    }
}