// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Livraria.Model
{
    public partial class DB_LIVRARIAContext : DbContext
    {
        public DB_LIVRARIAContext()
        {
        }

        public DB_LIVRARIAContext(DbContextOptions<DB_LIVRARIAContext> options)
            : base(options)
        {
        }

        public virtual DbSet<tbl_Aluno> tbl_Aluno { get; set; }
        public virtual DbSet<tbl_Livros> tbl_Livros { get; set; }
        public virtual DbSet<tbl_Pedido> tbl_Pedido { get; set; }
        public virtual DbSet<tbl_atendente> tbl_atendente { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder.UseSqlServer("Server=.\\SQLExpress;Database=DB_LIVRARIA;Trusted_Connection=True;trustservercertificate=true");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<tbl_Aluno>(entity =>
            {
                entity.HasKey(e => e.cd_Aluno)
                    .HasName("PK__tbl_Alun__129D0BD78B93AF58");

                entity.Property(e => e.nm_Curso)
                    .IsRequired()
                    .HasMaxLength(60)
                    .IsUnicode(false);

                entity.Property(e => e.nm_Email)
                    .IsRequired()
                    .HasMaxLength(60)
                    .IsUnicode(false);

                entity.Property(e => e.nm_Nome)
                    .IsRequired()
                    .HasMaxLength(60)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<tbl_Livros>(entity =>
            {
                entity.HasKey(e => e.cd_Livro)
                    .HasName("PK__tbl_Livr__93FCE396760FA8B6");

                entity.Property(e => e.nm_Assunto)
                    .IsRequired()
                    .HasMaxLength(60)
                    .IsUnicode(false);

                entity.Property(e => e.nm_Autor)
                    .IsRequired()
                    .HasMaxLength(60)
                    .IsUnicode(false);

                entity.Property(e => e.nm_Editora)
                    .IsRequired()
                    .HasMaxLength(60)
                    .IsUnicode(false);

                entity.Property(e => e.nm_Titulo)
                    .IsRequired()
                    .HasMaxLength(60)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<tbl_Pedido>(entity =>
            {
                entity.HasKey(e => e.cd_Pedido)
                    .HasName("PK__tbl_Pedi__474D2A40ABA2394C");

                entity.Property(e => e.dt_Devolucao).HasColumnType("datetime");

                entity.Property(e => e.nm_Aluno)
                    .IsRequired()
                    .HasMaxLength(60)
                    .IsUnicode(false);

                entity.Property(e => e.nm_Atendente)
                    .IsRequired()
                    .HasMaxLength(60)
                    .IsUnicode(false);

                entity.Property(e => e.nm_Livro)
                    .IsRequired()
                    .HasMaxLength(60)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<tbl_atendente>(entity =>
            {
                entity.HasKey(e => e.cd_Atendente)
                    .HasName("PK__tbl_aten__04B2C28AD8718E33");

                entity.Property(e => e.ds_Login)
                    .IsRequired()
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.ds_Senha)
                    .IsRequired()
                    .HasMaxLength(8)
                    .IsUnicode(false)
                    .IsFixedLength();

                entity.Property(e => e.ds_status)
                    .IsRequired()
                    .HasDefaultValueSql("((1))");

                entity.Property(e => e.nm_Atendente)
                    .IsRequired()
                    .HasMaxLength(60)
                    .IsUnicode(false);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}