// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Livraria.Model
{
    public partial class tbl_Aluno
    {
        public int cd_Aluno { get; set; }
        public string nm_Nome { get; set; }
        public string nm_Email { get; set; }
        public string nm_Curso { get; set; }
    }
}