// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Livraria.Model
{
    public partial class tbl_atendente
    {
        public int cd_Atendente { get; set; }
        public string ds_Login { get; set; }
        public string ds_Senha { get; set; }
        public string nm_Atendente { get; set; }
        public bool? ds_status { get; set; }
    }
}