// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Livraria.Model
{
    public partial class tbl_Pedido
    {
        public int cd_Pedido { get; set; }
        public string nm_Aluno { get; set; }
        public string nm_Livro { get; set; }
        public string nm_Atendente { get; set; }
        public DateTime dt_Devolucao { get; set; }
    }
}