// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Livraria.Model
{
    public partial class tbl_Livros
    {
        public int cd_Livro { get; set; }
        public string nm_Titulo { get; set; }
        public string nm_Autor { get; set; }
        public string nm_Assunto { get; set; }
        public string nm_Editora { get; set; }
    }
}